[package]
name = "intra-office-ai-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
objc2-core-foundation = "0.3.1"
tokio = { version = "1.45.0", features = ["full"] }
tray-icon = "0.20.1"
warp = "0.3.7"
winit = "0.30.11"
